# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Im0H8d7IgIlCu3JEC97_oE4AhqB9DrCw
"""

!pip install wget

import wget
url="https://s3.amazonaws.com/coderbyteprojectattachments/biourja-efzrr-y7i38ed9-input.csv"
file=wget.download(url)

import pandas as pd
df=pd.read_csv(file)
df.head()
df1=pd.read_csv(file)

for i,x in enumerate(df['Plant_Name']):
  df.iloc[i,df.columns.get_loc('Plant_Name')] = x[0]
df.head()

a=df.groupby('Plant_Name')
total_Forecast=a['Forecast'].sum()
total_Capacity=a['Capacity'].sum()
grouped = df.groupby('Plant_Name').agg({'Forecast': 'sum', 'Capacity': 'sum'}).reset_index()
grouped.head()

total_state_forecast= df['Forecast'].sum()
print(total_state_forecast)

weight=(df1.Forecast/df1.Capacity)
df1["Weight"]=weight

df1.head()

norm_weight = df1['Weight']/(df1['Weight'].sum())
df1['Norm_Weight']=norm_weight

df1.head()

new_forecast = total_state_forecast*df1['Norm_Weight']
df1['new_forecast']=new_forecast
for index, row in df1.iterrows():
    if row['new_forecast'] <= row['Capacity']:
        df1.at[index, 'new_forecast'] = row['new_forecast']
    else:
        df1.at[index, 'new_forecast'] = row['Capacity']

df1.head()

new_forecast=df1['new_forecast'].sum()
adjustment= 12000/new_forecast
adjusted_forecast=df1['new_forecast']*adjustment
df1['adjusted_forecast']=adjusted_forecast

df1.head()

df1['adjusted_forecast'].sum()

df.to_csv('wind_farm_new.csv',index=False)

